version: "3.9"

services:
  devopsdb:
    image: rkdocker1800/auto:db
    ports:
      - "3306:3306"
    deploy:
      replicas: 5
    networks:
      - mynetwork

  application:
    image: rkdocker1800/auto:app
    ports:
      - "1111:8080"
    deploy:
      replicas: 5
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
